language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls
before_script:
  - export PYTHONPATH=`pwd`
# command to run tests
script: 
  - coverage run note_tests.py
after_success:
  - coverallslanguage: python
  - coveralls